[tool.semantic_release]
version = "1.0.2"
version_variable = [
    "pyproject.toml:version"
]
version_pattern = [
    "{{cookiecutter.project_slug}}/README.md:.+blueprint-general/tree/v{version}"
]
upload_to_pypi = false
upload_to_release = false
commit_subject = "chore(release): {version} [skip actions]"
